<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5900" started-at="2021-05-05T11:42:12 IST" finished-at="2021-05-05T11:42:17 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5900" started-at="2021-05-05T11:42:12 IST" finished-at="2021-05-05T11:42:17 IST">
      <class name="day3.TestWithPageFactory">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:day3.TestWithPageFactory@12c8a2c0]" name="beforeTest" is-config="true" duration-ms="1958" started-at="2021-05-05T11:42:12 IST" finished-at="2021-05-05T11:42:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="tc01()[pri:0, instance:day3.TestWithPageFactory@12c8a2c0]" name="tc01" duration-ms="2839" started-at="2021-05-05T11:42:14 IST" finished-at="2021-05-05T11:42:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01 -->
        <test-method status="PASS" signature="getResults(org.testng.ITestResult)[pri:0, instance:day3.TestWithPageFactory@12c8a2c0]" name="getResults" is-config="true" duration-ms="3" started-at="2021-05-05T11:42:16 IST" finished-at="2021-05-05T11:42:16 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tc01 status=SUCCESS method=TestWithPageFactory.tc01()[pri:0, instance:day3.TestWithPageFactory@12c8a2c0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResults -->
        <test-method status="FAIL" signature="tc02()[pri:1, instance:day3.TestWithPageFactory@12c8a2c0]" name="tc02" duration-ms="663" started-at="2021-05-05T11:42:16 IST" finished-at="2021-05-05T11:42:17 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Home] but found [Demo Web Shop. Register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Home] but found [Demo Web Shop. Register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at day3.TestWithPageFactory.tc02(TestWithPageFactory.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02 -->
        <test-method status="PASS" signature="getResults(org.testng.ITestResult)[pri:0, instance:day3.TestWithPageFactory@12c8a2c0]" name="getResults" is-config="true" duration-ms="143" started-at="2021-05-05T11:42:17 IST" finished-at="2021-05-05T11:42:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tc02 status=FAILURE method=TestWithPageFactory.tc02()[pri:1, instance:day3.TestWithPageFactory@12c8a2c0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResults -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:day3.TestWithPageFactory@12c8a2c0]" name="afterTest" is-config="true" duration-ms="238" started-at="2021-05-05T11:42:17 IST" finished-at="2021-05-05T11:42:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- day3.TestWithPageFactory -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
